### ISSUE TITLE
TaskCatTempBucket is never used

### ISSUE THREAD

**Issue by jamestharpe** [aws-samples/aws-service-catalog-reference-architectures#30]
TaskCatTempBucket is never used: https://github.com/aws-samples/aws-service-catalog-reference-architectures/blob/a3b7d369848a1396390752c890ff8683b19818d3/codepipeline/sc-codepipeline-ra.json#L40

I also checked Taskcats repository and found no references to `TaskCatTempBucket` or `taskcat-tempbucket`.

**Comment by jamestharpe** [comment]
It appears the same is true for `ScratchBucket`

**Comment by chapmancl** [comment]
yep, relics from an older setup. removed in #31
