### ISSUE TITLE
Issue with this usecase: Shared portfolio from Hub Account

### ISSUE THREAD

**Issue by Larry322** [aws-samples/aws-service-catalog-reference-architectures#47]
Hi 
Not sure if this use case is support. I tried it, not able to make it work.

I'm installing the protfolios on the Hub Account only and then trying to share it with the spoke accounts. The portfolio appears on the Spoke account (under imported portfolio).. but the produts are not available on the products list.

Is it because of the constraints created on the products?

Any thoughts?

Thanks!

**Comment by chapmancl** [comment]
you must add principals to portfolios to see the products.  Add principals to an imported portfolio at the child account or import the products into a local portfolio and add the users to the local portfolio.  
https://docs.aws.amazon.com/servicecatalog/latest/adminguide/catalogs_portfolios_sharing.html

**Comment by Larry322** [comment]
After adding principals I am able to see the product lists in spoke account. However when I launch the product from the spoke account (not the hub acccount), the stack is created in the Hub Account. 

Git --> Pipeline (Hub Account) --> Portfolio (Hub Account) -> Shared with Spoke Account

Spoke Account --> Launch Products --> Creating the product in Hub Accout

Am I missing something? Thanks for your help.
