### ISSUE TITLE
what is the difference between taskcat.yml and taskcat-all.yml ?

### ISSUE THREAD

**Issue by zaro0508** [aws-samples/aws-service-catalog-reference-architectures#54]
What is the difference between ci/taskcat.yml and ci/taskcat-all.yml?    it looks like ci/buildspec-validate.yml is setup to run ci/taskcat.yml.  When I attempt to run taskcat with [ci/taskcat.yml i get failures](https://pastebin.com/ddv6EiWF) however when I run with [ci/taskcat-all.yml all tests pass](https://pastebin.com/hkyL1b0s).  I took a quick look at both and they seem to run the same tests to me.  Am I missing something?  Why is one failing while the other is passing?

**Comment by chapmancl** [comment]
taskcat-all.yml is used for testing the all the portfolios as part of this repo's validation.  taskcat.yml is a skeleton for the implementing user to see how the reference pipeline can validate templates in their environment.
