### ISSUE TITLE
Error when running pipeline, logicalid stackServiceCatalogEndusers

### ISSUE THREAD

**Issue by viniza** [aws-samples/aws-service-catalog-reference-architectures#71]
When running the pipeline, the build runs cloudformation update-stack-set to update the portfolio stack. The CloudFormation update fails with the following error:

Logical Id: stackServiceCatalogEndusers
The following resource(s) failed to create: [SCEnduserRole, SCEnduserGroup].

The reason is that the parameter "CreateEndUsers" is missing (which defaults to "Yes"), so it tries to create the mentioned resources when they were provisioned in a previous step.

Affected command:

- aws cloudformation update-stack-set --stack-set-name SC-IAC-automated-portfolio --parameters "[{\"ParameterKey\":\"LinkedRole2\",\"UsePreviousValue\":true},{\"ParameterKey\":\"LinkedRole1\",\"UsePreviousValue\":true},{\"ParameterKey\":\"LaunchRoleName\",\"UsePreviousValue\":true},{\"ParameterKey\":\"RepoRootURL\",\"ParameterValue\":\"https://s3.amazonaws.com/servicesatalog-deployedtemplates-$ACCID/\"}]" --template-url "https://s3.amazonaws.com/servicesatalog-deployedtemplates-$ACCID/ec2/sc-portfolio-ec2VPC.json"

Proposed fix:

- aws cloudformation update-stack-set --stack-set-name SC-IAC-automated-portfolio --parameters "[{\"ParameterKey\":\"LinkedRole2\",\"UsePreviousValue\":true},{\"ParameterKey\":\"CreateEndUsers\",\"UsePreviousValue\":true},{\"ParameterKey\":\"LinkedRole1\",\"UsePreviousValue\":true},{\"ParameterKey\":\"LaunchRoleName\",\"UsePreviousValue\":true},{\"ParameterKey\":\"RepoRootURL\",\"ParameterValue\":\"https://$DEPLOY_BUCKET.s3.amazonaws.com/\"}]" --template-url "https://$DEPLOY_BUCKET.s3.amazonaws.com/ec2/sc-portfolio-ec2demo.json" --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND

**Comment by chapmancl** [comment]
Thanks for that, I added the parameter to the update-stack calls.
